name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us reproduce and fix the issue.
  
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform(s) are you seeing this issue on?
      multiple: true
      options:
        - iOS
        - Android
        - Both
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device & OS Version
      description: What device and OS version are you using? (e.g., iPhone 14 iOS 17.2, Pixel 7 Android 14)
      placeholder: iPhone 14 Pro iOS 17.2
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of POWR are you running?
      placeholder: 1.0.0
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue and what you expected to happen instead
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Clear steps to reproduce the behavior
      placeholder: |
        1. Open the app
        2. Navigate to...
        3. Click on...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or error messages
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here (screenshots, videos, etc.)