name: Documentation Update
description: Help us improve our documentation
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve POWR's documentation!
        Please provide details about what needs to be updated or added.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs updating?
      options:
        - README
        - API Documentation
        - Setup Guide
        - Tutorial
        - Code Comments
        - Other
    validations:
      required: true

  - type: input
    id: page-link
    attributes:
      label: Documentation Link/Location
      description: Which document or section needs updating? Provide a link if available.
      placeholder: https://github.com/yourusername/powr/blob/main/docs/...

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the current documentation say? (if applicable)

  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      description: What would you like to add, remove, or modify?
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason for Change
      description: Why should this documentation be updated?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation update here